import prisma from "./prisma.client.js";

async function main() {
    await prisma.location.createMany({
        data: [
        { city: "Banda Aceh" },
        { city: "Langsa" },
        { city: "Lhokseumawe" },
        { city: "Sabang" },
        { city: "Subulussalam" },
        { city: "Denpasar" },
        { city: "Pangkalpinang" },
        { city: "Cilegon" },
        { city: "Serang" },
        { city: "Tangerang Selatan" },
        { city: "Tangerang" },
        { city: "Bengkulu" },
        { city: "Jakarta Pusat" },
        { city: "Jakarta Selatan" },
        { city: "Jakarta Timur" },
        { city: "Jakarta Utara" },
        { city: "Gorontalo" },
        { city: "Sungai Penuh" },
        { city: "Jambi" },
        { city: "Bandung" },
        { city: "Bekasi" },
        { city: "Bogor" },
        { city: "Cimahi" },
        { city: "Cirebon" },
        { city: "Depok" },
        { city: "Sukabumi" },
        { city: "Tasikmalaya" },
        { city: "Banjar" },
        { city: "Magelang" },
        { city: "Pekalongan" },
        { city: "Salatiga" },
        { city: "Semarang" },
        { city: "Surakarta" },
        { city: "Tegal" },
        { city: "Batu" },
        { city: "Blitar" },
        { city: "Kediri" },
        { city: "Madiun" },
        { city: "Malang" },
        { city: "Mojokerto" },
        { city: "Pasuruan" },
        { city: "Probolinggo" },
        { city: "Surabaya" },
        { city: "Pontianak" },
        { city: "Singkawang" },
        { city: "Banjarbaru" },
        { city: "Banjarmasin" },
        { city: "Palangka Raya" },
        { city: "Bontang" },
        { city: "Samarinda" },
        { city: "Nusantara" },
        { city: "Tarakan" },
        { city: "Batam" },
        { city: "Tanjungpinang" },
        { city: "Bandar Lampung" },
        { city: "Metro" },
        { city: "Ternate" },
        { city: "Tidore Kepulauan" },
        { city: "Ambon" },
        { city: "Tual" },
        { city: "Bima" },
        { city: "Mataram" },
        { city: "Kupang" },
        { city: "Sorong" },
        { city: "Jayapura" },
        { city: "Dumai" },
        { city: "Pekanbaru" },
        { city: "Makassar" },
        { city: "Palopo" },
        { city: "Parepare" },
        { city: "Palu" },
        { city: "Baubau" },
        { city: "Kendari" },
        { city: "Bitung" },
        { city: "Kotamobagu" },
        { city: "Manado" },
        { city: "Tomohon" },
        { city: "Bukittinggi" },
        { city: "Padang" },
        { city: "Padang Panjang" },
        { city: "Pariaman" },
        { city: "Payakumbuh" },
        { city: "Sawahlunto" },
        { city: "Solok" },
        { city: "Lubuklinggau" },
        { city: "Pagar Alam" },
        { city: "Palembang" },
        { city: "Prabumulih" },
        { city: "Binjai" },
        { city: "Gunungsitoli" },
        { city: "Medan" },
        { city: "Padangsidimpuan" },
        { city: "Pematangsiantar" },
        { city: "Sibolga" },
        { city: "Tanjungbalai" },
        { city: "Tebing Tinggi" },
        ],
    });
    }

    main()
    .then(() => {
        console.log("Seeding completed.");
    })
    .catch((error) => {
        console.error("Seeding error:", error);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
